name: Susani
description: Susani User Application
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.0.6+40
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.3.8
  fancy_bottom_navigation: ^0.3.2
  carousel_slider: ^4.0.0
  flutter_staggered_grid_view: ^0.4.0
  http: ^1.2.0
  convert: ^3.0.1
  font_awesome_flutter: ^10.7.0
  lottie: ^3.1.2
  flutter_spinkit: ^5.1.0
  webview_flutter:
  flutter_rating_bar: ^4.0.0
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.1.0
  shimmer: ^3.0.0
  intl: ^0.19.0
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.0.15
  shared_preferences: ^2.0.9
  flutter_launcher_icons: ^0.13.1
  sliding_up_panel: ^2.0.0+1
  file_picker:
  http_auth: ^1.0.1
  image_cropper: ^6.0.0
  flutter_holo_date_picker: ^1.0.3
  geolocator:
  permission_handler: any
  table_calendar: ^3.0.6
  flutter_inappwebview: ^5.4.3+7
  contactus: ^1.2.0
  photo_view: ^0.15.0
  badges: ^3.1.2
  restart_app: ^1.1.2
  razorpay_flutter: ^1.3.7
  video_player_web:



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/lsd.png"

dev_dependencies:
  
  flutter_test:
    sdk: flutter



flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/logo/
     - assets/icon/ 
     - assets/images/ 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

